namespace CScript
{
    [System.Serializable]
    public enum Opcodes
    {
        // PUSH
        PUSH_BYTE, PUSH_SBYTE, PUSH_SHORT, PUSH_USHORT, PUSH_INT, PUSH_UINT, PUSH_LONG, PUSH_ULONG, PUSH_FLOAT, PUSH_DOUBLE,
        
        // POP
        POP_BYTE, POP_SBYTE, POP_SHORT, POP_USHORT, POP_INT, POP_UINT, POP_LONG, POP_ULONG, POP_FLOAT, POP_DOUBLE,
        
        // ADD
        ADD_BYTE, ADD_SBYTE, ADD_SHORT, ADD_USHORT, ADD_INT, ADD_UINT, ADD_LONG, ADD_ULONG, ADD_FLOAT, ADD_DOUBLE,
        
        // SUB
        SUB_BYTE, SUB_SBYTE, SUB_SHORT, SUB_USHORT, SUB_INT, SUB_UINT, SUB_LONG, SUB_ULONG, SUB_FLOAT, SUB_DOUBLE,
        
        // MUL
        MUL_BYTE, MUL_SBYTE, MUL_SHORT, MUL_USHORT, MUL_INT, MUL_UINT, MUL_LONG, MUL_ULONG, MUL_FLOAT, MUL_DOUBLE,
        
        // DIV
        DIV_BYTE, DIV_SBYTE, DIV_SHORT, DIV_USHORT, DIV_INT, DIV_UINT, DIV_LONG, DIV_ULONG, DIV_FLOAT, DIV_DOUBLE,
        
        // EQUALITY
        
        EQUAL_BYTE, EQUAL_SBYTE, EQUAL_SHORT, EQUAL_USHORT, EQUAL_INT, EQUAL_UINT, EQUAL_LONG, EQUAL_ULONG, EQUAL_FLOAT, EQUAL_DOUBLE,
        NOT_EQUAL_BYTE, NOT_EQUAL_SBYTE, NOT_EQUAL_SHORT, NOT_EQUAL_USHORT, NOT_EQUAL_INT, NOT_EQUAL_UINT, NOT_EQUAL_LONG, NOT_EQUAL_ULONG, NOT_EQUAL_FLOAT, NOT_EQUAL_DOUBLE,
        GREATER_THAN_BYTE, GREATER_THAN_SBYTE, GREATER_THAN_SHORT, GREATER_THAN_USHORT, GREATER_THAN_INT, GREATER_THAN_UINT, GREATER_THAN_LONG, GREATER_THAN_ULONG, GREATER_THAN_FLOAT, GREATER_THAN_DOUBLE, 
        GREATER_EQUAL_BYTE, GREATER_EQUAL_SBYTE, GREATER_EQUAL_SHORT, GREATER_EQUAL_USHORT, GREATER_EQUAL_INT, GREATER_EQUAL_UINT, GREATER_EQUAL_LONG, GREATER_EQUAL_ULONG, GREATER_EQUAL_FLOAT, GREATER_EQUAL_DOUBLE, 
        LESS_BYTE, LESS_SBYTE, LESS_SHORT, LESS_USHORT, LESS_INT, LESS_UINT, LESS_LONG, LESS_ULONG, LESS_FLOAT, LESS_DOUBLE, 
        LESS_EQUAL_BYTE, LESS_EQUAL_SBYTE, LESS_EQUAL_SHORT, LESS_EQUAL_USHORT, LESS_EQUAL_INT, LESS_EQUAL_UINT, LESS_EQUAL_LONG, LESS_EQUAL_ULONG, LESS_EQUAL_FLOAT, LESS_EQUAL_DOUBLE,
        
        // Flow control
        JMP, JMP_IF_TRUE, JMP_IF_FALSE, CALL, RET,
        
        OPCODE_COUNT
    }
}
