namespace CScript
{
    [System.Serializable]
    public enum Opcodes
    {
        DEBUG,
        
        // PUSH
        PUSH,
        
        // POP
        POP,
        
        // COPY
        DUPLICATE,
        
        // MOVE
        MOVE_TO_REGISTER,
        
        // LOAD
        LOAD_REGISTER,
        
        // ADD
        ADD, ADD_BYTE, ADD_SBYTE, ADD_SHORT, ADD_USHORT, ADD_INT, ADD_UINT, ADD_LONG, ADD_ULONG, ADD_FLOAT, ADD_DOUBLE,
        
        // SUB
        SUB, SUB_BYTE, SUB_SBYTE, SUB_SHORT, SUB_USHORT, SUB_INT, SUB_UINT, SUB_LONG, SUB_ULONG, SUB_FLOAT, SUB_DOUBLE,
        
        // MUL
        MUL, MUL_BYTE, MUL_SBYTE, MUL_SHORT, MUL_USHORT, MUL_INT, MUL_UINT, MUL_LONG, MUL_ULONG, MUL_FLOAT, MUL_DOUBLE,
        
        // DIV
        DIV, DIV_BYTE, DIV_SBYTE, DIV_SHORT, DIV_USHORT, DIV_INT, DIV_UINT, DIV_LONG, DIV_ULONG, DIV_FLOAT, DIV_DOUBLE,
        
        // EQUALITY
        
        EQUAL, NOT_EQUAL,
        GREATER_THAN_BYTE, GREATER_THAN_SBYTE, GREATER_THAN_SHORT, GREATER_THAN_USHORT, GREATER_THAN_INT, GREATER_THAN_UINT, GREATER_THAN_LONG, GREATER_THAN_ULONG, GREATER_THAN_FLOAT, GREATER_THAN_DOUBLE, 
        GREATER_EQUAL_BYTE, GREATER_EQUAL_SBYTE, GREATER_EQUAL_SHORT, GREATER_EQUAL_USHORT, GREATER_EQUAL_INT, GREATER_EQUAL_UINT, GREATER_EQUAL_LONG, GREATER_EQUAL_ULONG, GREATER_EQUAL_FLOAT, GREATER_EQUAL_DOUBLE, 
        LESS_BYTE, LESS_SBYTE, LESS_SHORT, LESS_USHORT, LESS_INT, LESS_UINT, LESS_LONG, LESS_ULONG, LESS_FLOAT, LESS_DOUBLE, 
        LESS_EQUAL_BYTE, LESS_EQUAL_SBYTE, LESS_EQUAL_SHORT, LESS_EQUAL_USHORT, LESS_EQUAL_INT, LESS_EQUAL_UINT, LESS_EQUAL_LONG, LESS_EQUAL_ULONG, LESS_EQUAL_FLOAT, LESS_EQUAL_DOUBLE,
        
        // Flow control
        JMP, JMP_IF_TRUE, JMP_IF_FALSE, CALL, RET,
        
        OPCODE_COUNT,
    }
}
