namespace Riten.CScript.Native
{
    public enum Opcodes : int
    {
        JMP_IF_TOP_ZERO,
        JMP_IF_ZERO,
        JMP,
        CALL,
        CALL_ARGS,
        RETURN,
        STOP,
        ADD,
        ADD_CONST,
        ADD_CONST_TO_SPTR,
        ADD_SPTR_SPTR_INTO_SPTR,
        PUSH_CONST,
        PUSH_SPTR,
        PUSH_SPTR_AND_CONST,
        PUSH_CONST_TO_SPTR,
        POP,
        POP_TO_SPTR,
        RESERVE,
        DISCARD,
        DUP,
        SWAP_SPTR_SPTR,
        REPEAT,
        REPEAT_CONST,
        REPEAT_SPTR,
        REPEAT_END,
        COPY_FROM_SPTR_TO_SPTR,
        LESS_OR_EQUAL,
    }
}